apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-python
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/luchenzo7/EKS_Deployment.git
    targetRevision: gitops
    path: helm/hello-python
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: hello-python

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
